#!/usr/bin/env bash

# launch-agents aliases
alias law='launch-agents workspace'
alias la2='launch-agents -n 2 --daemon start'
alias la4='launch-agents -n 4 start'
alias la6='launch-agents -n 6 start'
alias las='launch-agents stop'
alias lac='launch-agents --force clean'
