#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install --cask claude-code || brew upgrade --cask claude-code
brew install --cask claude || brew upgrade --cask claude

export PATH=$TMPPATH
