#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# Ruby Gem - XDG compliant
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# Ruby IRB history - XDG compliant
export IRBRC="$XDG_CONFIG_HOME/irb/irbrc"
export IRB_HISTORY_FILE="$XDG_STATE_HOME/irb/history"
mkdir -p "$XDG_STATE_HOME/irb" 2>/dev/null
mkdir -p "$XDG_CONFIG_HOME/irb" 2>/dev/null
