#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install --cask ghostty || brew upgrade --cask ghostty
brew install --cask font-jetbrains-mono-nerd-font || brew upgrade --cask font-jetbrains-mono-nerd-font

export PATH=$TMPPATH
