#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install jless || brew upgrade jless
brew install flock || brew upgrade flock
brew install htop || brew upgrade htop
brew install openssl || brew upgrade openssl
brew unlink openssl && brew link --force openssl
# brew install gnupg || brew upgrade gnupg
brew install --cask ghostty || brew upgrade ghostty
brew install --cask font-jetbrains-mono || brew upgrade font-jetbrains-mono
# brew install --cask iterm2 || brew upgrade iterm2

packages=(fd jq yq git-delta fzf bat eza ripgrep tldr glow)
for pkg in "${packages[@]}"; do
    brew install "$pkg" || brew upgrade "$pkg"
done

brew install mkcert || brew upgrade mkcert
mkcert -install

export PATH=$TMPPATH
