#!/usr/bin/env bash

alias gall='git add --all'
alias gc='git commit'
alias gca='git commit -a'
alias gp='git push origin'
alias gch='git checkout'
alias gb='git branch'
alias gs='git status -sb' # upgrade your git if -sb breaks for you. it's fun.
