#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install git || brew upgrade git
brew install gitlab-ci-multi-runner || brew upgrade gitlab-ci-multi-runner

export PATH=$TMPPATH
