#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install git || brew upgrade git
brew install gh || brew upgrade gh
brew install lazygit || brew upgrade lazygit

export PATH=$TMPPATH
