#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install git || brew upgrade git
brew install gh || brew upgrade gh
brew install lazygit || brew upgrade lazygit

export PATH=$TMPPATH
