#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install --cask mactex-no-gui || brew upgrade mactex-no-gui
brew install biber || brew upgrade biber
brew install --cask bibdesk || brew upgrade bibdesk

export PATH=$TMPPATH
