#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: 
#   http://sourabhbajaj.com/mac-setup/Vagrant/README.html
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew cask install virtualbox
brew cask install vagrant
brew cask install vagrant-manager

export PATH=$TMPPATH
