#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


alias vimstall="vim +PluginInstall +qall" # command to install Vundle packages
alias noswp="rm -f *.swp"

# Neovim aliases
alias v="nvim"
alias vi="nvim"
alias nv="nvim"
alias nvimup="nvim --headless '+Lazy! sync' +qa"  # Update neovim plugins
