#!/usr/bin/env bash

workdir () { cd $WORK_DIR/$1 ; }
alias cdw='workdir'

bu () { cp $1 ~/tmp/`basename $1`-`date +%Y%m%d%H%M`.backup ; }

# Change working directory to the top-most Finder window location
cdfinder () {
    cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}
alias cdf='cdfinder'

# Determine size of a file or total size of a directory
fs () {
    if du -b /dev/null > /dev/null 2>&1; then
        local arg=-sbh;
    else
        local arg=-sh;
    fi
    if [[ -n "$@" ]]; then
        du $arg -- "$@";
    else
        du $arg *;
    fi;
}

# Create a git.io short URL
function gitio() {
    if [ -z "${1}" -o -z "${2}" ]; then
        echo "Usage: \`gitio slug url\`";
        return 1;
    fi;
    curl -i http://git.io/ -F "url=${2}" -F "code=${1}";
}

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
