#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install tmux || brew upgrade tmux

export PATH=$TMPPATH
