#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


alias noswp="rm -f *.swp"

# Neovim aliases
alias vi="nvim"
alias nv="nvim"
alias nvimup="nvim --headless '+Lazy! sync' +qa && echo '✓ Plugins updated successfully'"  # Update neovim plugins
