#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

# only want the latest and greatest
brew install nvim || brew upgrade nvim


export PATH=$TMPPATH
