#!/usr/bin/env bash

alias dk="docker ps -qa | xargs docker rm --force"
alias dc='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
alias gl='gitlab-runner exec docker'
alias kuc='kubectl config use-context'
