#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# http://postgresapp.com/documentation/gui-tools.html
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install kubernetes-cli
curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /usr/local/etc/bash_completion.d/docker-compose

export PATH=$TMPPATH
