#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# Runtimes come from brew, so only the state dirs need XDG redirection

# Wasmtime - XDG compliant
export WASMTIME_HOME="$XDG_DATA_HOME/wasmtime"

# Wasmer - XDG compliant, keeps registry/tokens out of ~/.wasmer
export WASMER_DIR="$XDG_DATA_HOME/wasmer"
export WASMER_CACHE_DIR="$XDG_CACHE_HOME/wasmer"
