#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install wasmtime || brew upgrade wasmtime
brew install wasmer || brew upgrade wasmer

brew tap spinframework/tap
brew trust --tap spinframework/tap
brew install spinframework/tap/spin || brew upgrade spinframework/tap/spin

export PATH=$TMPPATH
