#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install wasmtime || brew upgrade wasmtime
brew install wasmer || brew upgrade wasmer

export PATH=$TMPPATH
