#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install python@3.13 || brew upgrade python@3.13
brew install awscli || brew upgrade awscli

export PATH=$TMPPATH
