#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install --cask visual-studio-code || brew upgrade visual-studio-code

export PATH=$TMPPATH
