#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# Cargo - XDG compliant
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# Rustup - XDG compliant
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

export PATH="$CARGO_HOME/bin:$PATH"
