#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://thechangelog.com/install-node-js-with-homebrew-on-os-x/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install node || brew upgrade node

# sudoing this kills chown of man pageS
#sudo npm install -g npm@latest

export PATH=$TMPPATH
