#!/usr/bin/env bash

goclean () { ls $GOPATH/src | grep -v sbp.gitlab.schubergphilis.com | xargs rm -rf; }
cg () {
case $# in
    0) 
    cd $GOPATH/src/sbp.gitlab.schubergphilis.com
    ;;
    1)
    cd $GOPATH/src/sbp.gitlab.schubergphilis.com/$1
    ;;
esac
}
