#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install go || brew upgrade go
brew install --devel protobuf || brew upgrade --devel protobuf

brew linkapps go

export PATH=$TMPPATH
