#!/usr/bin/env bash

workon () { source $WORKON_DIR/$1/bin/activate ; }

function deactivate {
    local venv=basename $VIRTUAL_ENV
    export PS1=echo PS1 | sed "s/($venv)//"
    export PATH=${PATH#$VIRTUAL_ENV}
    unset VIRTUAL_ENV
}    

mkenv () { virtualenv --no-site-packages $WORKON_DIR/$1 ; }

showenv () { ls $WORKON_DIR ; }
