#!/usr/bin/env bash

workon () { source $WORKON_DIR/$1/bin/activate ; }
alias wo="workon"

function deactivate {
    local venv=basename $VIRTUAL_ENV
    export PS1=echo PS1 | sed "s/($venv)//"
    export PATH=${PATH#$VIRTUAL_ENV}
    unset VIRTUAL_ENV
}    

mkenv () { virtualenv --system-site-packages $WORKON_DIR/$1 ; }
mkenv3 () { virtualenv -p python3 --system-site-packages $WORKON_DIR/$1 ; }

showenv () { ls $WORKON_DIR ; }
alias se="showenv"
alias m="python -Wignore manage.py"
alias venv='source .*/bin/activate'
