#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


_dotfiles_cached_eval uv uv generate-shell-completion bash
complete -o "nospace" -W "python" killall;
_dotfiles_cached_eval pip3 pip3 completion --bash
