#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install python || brew upgrade python
brew install pipx || brew upgrade pipx
brew install virtualenv || brew upgrade virtualenv
brew install uv || brew upgrade uv
# we rely on uv noe
# brew install python@3.13 || brew upgrade python@3.13
# brew install python@3.14 || brew upgrade python@3.14
# brew install python || brew upgrade python
# brew unlink python@3.13 && brew link python@3.13

brew install readline || brew upgrade readline

pipx install podman-compose || pipx upgrade podman-compose

# minio
# brew install minio/stable/mc || brew upgrade minio/stable/mc

#pip install ansible


export PATH=$TMPPATH
