#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install python || brew upgrade python
brew linkapps python

sudo easy_install pip
sudo pip install --upgrade setuptools
sudo pip install --upgrade virtualenv
sudo pip install --upgrade pip

sudo pip install --upgrade autopep8
brew install readline --universal || brew upgrade readline

pip install ansible


export PATH=$TMPPATH
