#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

if ! brew install python
then
    brew upgrade python
fi

pip install --upgrade setuptools
pip install --upgrade pip

brew linkapps python

export PATH=$TMPPATH
