"Taken from: http://bilalquadri.com/blog/2012/12/17/getting-started-with-vim/"

" XDG Base Directory Support
" See: https://wiki.archlinux.org/title/XDG_Base_Directory
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME . '/.config' | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME = $HOME . '/.local/share' | endif
if empty($XDG_STATE_HOME)  | let $XDG_STATE_HOME = $HOME . '/.local/state' | endif
if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME = $HOME . '/.cache' | endif

" Create XDG directories for vim
let s:vim_state = $XDG_STATE_HOME . '/vim'
let s:vim_data  = $XDG_DATA_HOME . '/vim'
let s:vim_cache = $XDG_CACHE_HOME . '/vim'
for s:dir in [s:vim_state, s:vim_data, s:vim_cache,
            \ s:vim_state . '/swap', s:vim_state . '/backup', s:vim_state . '/undo']
    if !isdirectory(s:dir)
        call mkdir(s:dir, 'p', 0700)
    endif
endfor

" Move state files out of $HOME
" viminfofile is Vim-only; Neovim uses shada (handled automatically)
if !has('nvim')
  set viminfofile=$XDG_STATE_HOME/vim/viminfo
endif
set directory=$XDG_STATE_HOME/vim/swap//
set backupdir=$XDG_STATE_HOME/vim/backup//
set undodir=$XDG_STATE_HOME/vim/undo//
set undofile
let g:netrw_home = s:vim_state

" Basic settings
set nocompatible "Fixes old Vi bugs
syntax on
" http://www.terminally-incoherent.com/blog/2012/10/17/vim-solarized-and-tmux/
set t_Co=256 "Sets Vim to use 256 colors
let g:solarized_termcolors = 256
set background=dark
:silent! colorscheme solarized "make sure VIM works without scheme

set backspace=2 "Makes backspace work
set history=500 "Sets undo history size
set ruler "Sets up status bar
set laststatus=2 "Always keeps the status bar active
set number "Turns on line numbering
set textwidth=120 "Make it obvious where 80 characters is
set colorcolumn=+1

" http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
" pastetoggle removed - not needed in Neovim (bracketed paste is automatic)
if !has('nvim')
  set pastetoggle=<F2>
  set ttymouse=xterm2
endif
nnoremap <F2> :set invpaste paste?<CR>
set showmode

set mouse=a

set clipboard=unnamed


" Indentation settings
set tabstop=4 "Sets display width of tabs
set shiftwidth=4 "Sets indentation width
set autoindent "Turns on auto-indenting
set smartindent "Remembers previous indent when creating new lines
set expandtab "make sure tabs will be spaces
set list listchars=tab:»·,trail:·,nbsp:·


" Search settings
set hlsearch "Highlights search terms
set showmatch "Highlights matching parentheses
set ignorecase "Ignores case when searching
set smartcase "Unless you put some caps in your search term


" Key mappings
"Use jj instead of escape in insert mode
inoremap jj <Esc>`^


" Pane handling
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Refresh chrome from VIM
" https://gist.github.com/iheitlager/46cb7cb3d7e0d30fc98b
map <F4> :silent !osascript -e 'tell application "Google Chrome" to reload active tab of window 1' > /dev/null;<CR><CR> :redraw!<CR>


" Filetype commands
" http://ku1ik.com/2011/09/08/formatting-xml-in-vim-with-indent-command.html
au FileType xml setlocal equalprg=xmllint\ --format\ --recover\ -\ 2>/dev/null

"Setup vundle
filetype off    " Required

" Use XDG data directory for plugins
set rtp+=$XDG_DATA_HOME/vim/bundle/Vundle.vim
call vundle#begin($XDG_DATA_HOME . '/vim/bundle')

Plugin 'gmarik/Vundle.vim'    " Required
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tomtom/tcomment_vim'
Plugin 'pangloss/vim-javascript'
Plugin 'elzr/vim-json'

call vundle#end()
"Turn on plugin & indentation support for specific filetypes
filetype plugin indent on " Required
