#!/usr/bin/env bash

# tab completion for $WORK_DIR folders
[[ $(/bin/ls -A $WORK_DIR) ]] && complete -o "default" -o "nospace" -W"$(/bin/ls $WORK_DIR)" cdw
[[ $(/bin/ls -A ~/studies) ]] && complete -o "default" -o "nospace" -W"$(/bin/ls ~/studies/)" cds
[[ $(/bin/ls -A ~/papers) ]] && complete -o "default" -o "nospace" -W"$(/bin/ls ~/papers/)" cdp

