#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install openssl || brew upgrade openssl
brew unlink openssl && brew link --force openssl
brew install gnupg || brew upgrade gnupg
# Ok, we fell for the mouse integration, iterm2 it is
brew install --cask iterm2
brew install fd || brew upgrade fd
brew install jq || brew upgrade jq
brew install yq || brew upgrade yq

brew install mkcert || brew install mkcert
mkcert -install

export PATH=$TMPPATH
