#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install openssl || brew upgrade openssl
brew unlink openssl && brew link --force openssl
brew install gnupg || brew upgrade gnupg
brew install --cask ghostty | brew upgrade ghostty
# brew install --cask iterm2
brew install fd || brew upgrade fd
brew install jq || brew upgrade jq
brew install yq || brew upgrade yq
brew install delta || brew upgrade delta
brew install fzf || brew upgrade fzf

brew install mkcert || brew upgrade mkcert
mkcert -install

export PATH=$TMPPATH
