#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# https://robots.thoughtbot.com/tmux-copy-paste-on-os-x-a-better-future
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install tmux || brew upgrade tmux
brew install reattach-to-user-namespace || brew upgrade reattach-to-user-namespace

export PATH=$TMPPATH
