#!/usr/bin/env bash
# Copyright 2026 Ilja Heitlager
# SPDX-License-Identifier: Apache-2.0


# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew install bash-completion@2 || brew upgrade bash-completion@2
brew install zoxide || brew upgrade zoxide
brew install jless || brew upgrade jless
brew install flock || brew upgrade flock
brew install htop || brew upgrade htop

packages=(fd jq yq git-delta fzf bat eza ripgrep tldr glow)
for pkg in "${packages[@]}"; do
    brew install "$pkg" || brew upgrade "$pkg"
done


export PATH=$TMPPATH
