#!/usr/bin/env bash

# brew installer helper, normally run this from 'dot'
# check: http://docs.python-guide.org/en/latest/starting/install/osx/
TMPPATH=$PATH
PATH=/usr/local/bin:$PATH

brew tap homebrew/science
brew install r && brew upgrade r
brew cask install rstudio

defaults write org.R-project.R force.LANG en_US.UTF-8

brew linkapps

export PATH=$TMPPATH
